In [0]:
import numpy as np

In [0]:
v1 = np.array([1,2,3,4])

In [4]:
print(v1)

[1 2 3 4]


In [5]:
v1[3]

4

In [0]:
v1 = np.arange(5)

In [7]:
v1

array([0, 1, 2, 3, 4])

In [8]:
print(v1)

[0 1 2 3 4]


In [0]:
v4 = np.arange(1, 10, 2)

In [10]:
v4

array([1, 3, 5, 7, 9])

In [0]:
v5 = np.arange(1,10,2)**2

In [12]:
v5

array([ 1,  9, 25, 49, 81])

In [0]:
v5 = np.arange(1,10,2)**5

In [14]:
v5

array([    1,   243,  3125, 16807, 59049])

In [0]:
v2 = np.arange(3,10,2, dtype=int)

In [16]:
v2

array([3, 5, 7, 9])

In [0]:
v3 = np.arange(3.5, 10.5, 2, dtype=float)

In [18]:
v3

array([3.5, 5.5, 7.5, 9.5])

In [19]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [0]:
v2 = v1.reshape(2, 6)

In [21]:
print(v2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [22]:
v2 = v1.reshape(2,6, order='F')
print(v2)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [0]:
v1 = np.arange(1,5).reshape(2,2)

In [24]:
v1

array([[1, 2],
       [3, 4]])

In [25]:
print(np.add(v1, v1))

[[2 4]
 [6 8]]


In [27]:
print(np.subtract(v1, v1))

[[0 0]
 [0 0]]


In [28]:
print(np.multiply(v1, v1))

[[ 1  4]
 [ 9 16]]


In [29]:
print(np.dot(v1, v1))

[[ 7 10]
 [15 22]]


In [30]:
v1

array([[1, 2],
       [3, 4]])

In [31]:
v1 = np.arange(12)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
v2 = v1.reshape(2,6, order='C')
print(v2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [36]:
v2 = v1.reshape(2,6, order='F')
print(v2)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [0]:
import pandas as pd
from pandas import Series, DataFrame

In [42]:
a = Series([1,3,5,7])
a

0    1
1    3
2    5
3    7
dtype: int64

In [43]:
a.values

array([1, 3, 5, 7])

In [44]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [46]:
a2 = pd.Series([1,3,5,7], index=['a','b','c','d'])
a2

a    1
b    3
c    5
d    7
dtype: int64